## 测试算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train_test_split

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
# 进行乱序处理
shuffle_indexes = np.random.permutation(len(X))

In [8]:
shuffle_indexes

array([ 18,  81,   9, 100, 136,  64,  41,  87, 124, 125,  75,  16,  61,
       130, 117, 105,  15,  99,  74,  50,  35,  89,  86,  62, 126, 110,
        36,  21,  76,  52,   2, 121,  65,  83, 142, 118,  27,  93,  77,
        47,  78, 116,  95,  63,  53,  60,  23,   0,   7,  11,  69,  33,
        29, 108,  45, 123,   3,   5, 132,  43,  56,  66,  32,  94,  38,
        24, 146, 148,  12,  70, 138,  42,  97, 139, 120,  71, 127, 145,
        17, 133,  88,  73,  37, 144, 129, 114, 113,  30,  67,  68,   4,
        91, 128,  82,  14, 104,  34, 135,  84, 149, 122, 143, 119,  49,
        46,  13,  28, 103,  51, 109,  44, 106, 102, 141,  80,  85,  55,
        98,   6,  25,  96,  22, 112,  90, 111,  58,  54, 115,   1,  39,
        48,  79,  40,  72, 131,  31, 107,  10,  19, 140,   8,  57, 134,
        59, 137,  92, 101, 147,  26,  20])

In [9]:
# 设置测试数据集比例
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [10]:
test_size

30

In [11]:
# 前20%为测试数据集，后80%为训练数据集
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]

In [12]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [14]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 测试算法

In [15]:
from playML.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [17]:
from playML.kNN import KNNClassifier

In [18]:
my_knn_clf = KNNClassifier(k=3)

In [19]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [20]:
y_predict = my_knn_clf.predict(X_test)

In [21]:
y_predict

array([0, 0, 0, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 1, 0, 1, 1, 2, 0, 1, 1, 2,
       2, 2, 1, 2, 1, 0, 1, 0])

In [22]:
y_test

array([0, 0, 0, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 0, 1, 1, 2, 0, 1, 1, 2,
       2, 2, 1, 2, 1, 0, 1, 0])

In [24]:
# 预测准确个数
sum(y_predict == y_test)

29

In [25]:
# 预测准确率
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

## sklearn中的train_test_split

In [28]:
from sklearn.model_selection import train_test_split

In [32]:
# 调用并设置随机种子
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)